<?php /** @noinspection PhpUnused */

use Drupal\omnia\Service\EmailService;

/**
 * Implements hook_element_info_alter().
 */
function omnia_element_info_alter(array &$types): void
{
    $themeConfig = Drupal::config('system.theme');

    if (isset($types['toolbar'])) {
        if ($themeConfig->get('admin') == 'gin') {
            $types['toolbar']['#attached']['library'][] = 'omnia/admin_menu_icon_gin';
        }
        else {
            $types['toolbar']['#attached']['library'][] = 'omnia/admin_menu_icon_default';
        }
    }
}

/**
 * Implements hook_theme().
 * @throws ReflectionException
 * @noinspection PhpUnusedParameterInspection
 */
function omnia_theme($existing, $type, $theme, $path): array {
    $emailClasses = [];

    return EmailService::processHookTheme($emailClasses);
}

/**
 * Implements hook_mail().
 * @noinspection PhpUnusedParameterInspection
 */
function omnia_mail($key, &$message, $params): void
{
    EmailService::processHookMail($message, $params);
}